apiVersion: v1
kind: Service
metadata:
  name: {{ .Release.Name }}-api-rest
  labels:
    app: api-rest
spec:
  type: NodePort
  selector:
    app: api-rest
  ports:
    - port: 8080
      name: https
      targetPort: 8080
      protocol: TCP
      nodePort: 30010
    - port: 8081
      name: http
      targetPort: 8081
      protocol: TCP
      nodePort: 30011
