name: Release Artifacts
on:
  push:
    branches:
      - 'release/**'
      - 'develop'

jobs:
  kubectl-plugin:
    runs-on: ${{ matrix.os }}
    strategy:
      fail-fast: false
      matrix:
        include:
          - os: ubuntu-latest
            target: linux-musl
            arch: x86_64
          - os: macos-latest
            target: apple-darwin
            arch: x86_64
          - os: ubuntu-latest
            target: windows-gnu
            arch: x86_64
            suffix: .exe
    steps:
      - uses: actions/checkout@v3
        with:
          submodules: recursive
      - uses: cachix/install-nix-action@v18
        with:
          nix_path: nixpkgs=channel:nixos
          extra_nix_config: extra-platforms = aarch64-darwin
      - uses: cachix/cachix-action@v12
        with:
          name: mayastor-extensions
          authToken: '${{ secrets.CACHIX_AUTH_TOKEN }}'
      - run: |
          nix-build -A utils.release.${{ matrix.target }}.kubectl-plugin --arg incremental false ${{ matrix.system }}
      - uses: actions/upload-artifact@v3
        with:
          name: kubectl-mayastor-${{ matrix.arch }}-${{ matrix.target }}
          path: ./result/bin/kubectl-mayastor${{ matrix.suffix }}
          if-no-files-found: error
